# Generated by Django 5.1 on 2025-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('id_categoria', models.CharField(choices=[('ELECTRONICA', 'Electrónica'), ('ROPA', 'Ropa'), ('ALACENA', 'Alacena'), ('REFRIGERADOS', 'Refrigerados'), ('HIGIENE, SALUD, Y BELLEZA', 'Higiene, salud, y belleza'), ('HOGAR', 'Hogar'), ('DEPORTES', 'Deportes'), ('OTROS', 'Otros')], default='OTROS', max_length=100)),
                ('imagen_url', models.URLField(blank=True)),
                ('id_detalle_de_producto', models.IntegerField(choices=[(1020, '1020- Carnes Y Productos de Origen Animal'), (2030, '2030- Lacteos y Derivados'), (3040, '3040- Electronica y Accesorios'), (4050, '4050- Ropa y Calzado'), (5060, '5060- Articulos de Hogar'), (6070, '6070- Articulos de Deporte'), (7080, '7080- Suministros de Higiene y Belleza'), (8090, '8090- Productos Varios'), (0, 'N/A')], default=0)),
            ],
        ),
    ]
