# Generated by Django 5.2.7 on 2025-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.IntegerField(choices=[(1001, '1001 - Aromaterapia y Esencias Naturales'), (1002, '1002 - Aceites y Lociones para Masaje'), (1003, '1003 - Cuidado Facial (Mascarillas, Sérums, Cremas)'), (1004, '1004 - Cuidado Corporal (Exfoliantes, Cremas, Sales de Baño)'), (1005, '1005 - Belleza y Estética (Maquillaje, Uñas, Cabello)'), (1006, '1006 - Productos para Baño y Relajación'), (1007, '1007 - Accesorios Spa (Toallas, Velas, Difusores)'), (1008, '1008 - Salud y Bienestar (Herbolaria, Suplementos Naturales)'), (1099, '1099 - Otros Productos de Spa'), (0, '0000 - N/A')], default=1099),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_detalle_de_producto',
            field=models.CharField(choices=[('AROMATERAPIA', 'Aromaterapia'), ('CUIDADO FACIAL', 'Cuidado facial'), ('CUIDADO CORPORAL', 'Cuidado corporal'), ('MASAJES', 'Masajes y aceites'), ('BAÑO RELAJANTE', 'Baño relajante'), ('BELLEZA', 'Belleza y estética'), ('SALUD Y BIENESTAR', 'Salud y bienestar'), ('ACCESORIOS SPA', 'Accesorios de spa'), ('OTROS', 'Otros')], default='OTROS', max_length=50),
        ),
    ]
