# Generated by Django 5.2.6 on 2025-10-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_id_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='id_producto',
        ),
    ]
